spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/articlesDb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    url: jdbc:mysql://192.168.1.20:3306/articlesDb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: alex
    password: Sofia@1005

  application:
    name: SCIENTIST-SERVICE

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

server:
  port: 4001

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://172.17.0.2:8761/eureka/
      defaultZone: http://192.168.49.2:31002/eureka/
  instance:
    hostname: 192.168.49.2
    prefer-ip-address: true
#    hostname: 172.17.0.4
#    hostname: 192.168.1.20

#react:
#  admin:
#    api:
#      host: http://localhost:4001
#      use-snake-case: true